run:
  deadline: 1m

linters:
  enable-all: true
  disable:
    - gocyclo
    - gochecknoinits
    - gochecknoglobals
    - dupl
    - unparam
    - lll
    - varcheck
    - funlen
    - godox

issues:
  exclude-rules:
    - text: "Use of weak random number generator"
      linters:
        - gosec
    - text: "comment on exported var"
      linters:
        - golint
    - text: "ST1003:"
      linters:
        - stylecheck

linters-settings:
  dogsled:
    max-blank-identifiers: 3
