name: NFT
on: [pull_request]
jobs:
  unit-test: 
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-go@v1
      with:
        go-version: 1.13
      id: go
    - name: Setup env for GO
    #  this is only used until the setup-go action is updated
      run: |
        echo "::set-env name=GOPATH::$(go env GOPATH)"
        echo "::add-path::$(go env GOPATH)/bin"
      shell: bash
    - uses: actions/checkout@v1
    - name: Unit_test
      run: cd incubator/nft && make test && pwd
